from __future__ import annotations

import json
from typing import Any

from agentscope.tool import FunctionTool
from pydantic import BaseModel, Field

from vla_data_juicer_agents.navigation.models import NavigationRequest, WorkflowPlan
from vla_data_juicer_agents.navigation.profiles import get_profile


class WorkflowPlanDraftState(BaseModel):
    request: NavigationRequest
    dataset_profile: str | None = None
    finalized_plan: WorkflowPlan | None = None
    validation_errors: list[str] = Field(default_factory=list)

    @property
    def date(self) -> str:
        return self.request.date

    @property
    def segments(self) -> list[str] | None:
        return self.request.segments

    @property
    def scene_mode(self) -> str | None:
        return self.request.scene_mode

    def missing_fields(self) -> list[str]:
        missing = []
        if self.scene_mode not in {"in", "out"}:
            missing.append("scene_mode")
        if self.dataset_profile is None:
            missing.append("dataset_profile")
        if self.finalized_plan is None:
            missing.append("finalized_plan")
        return missing

    def schema_snapshot(self) -> dict[str, Any]:
        return {
            "date": self.date,
            "segments": self.segments,
            "scene_mode": self.scene_mode or "<in|out>",
            "dataset_profile": self.dataset_profile or "<u_legacy_like|go2w_like>",
            "steps": "<generated by finalize_workflow_plan_tool after dataset_profile is valid>",
            "missing_fields": self.missing_fields(),
            "allowed_dataset_profiles": ["u_legacy_like", "go2w_like"],
            "allowed_tool_order": [
                "prepare_raw_data",
                "extract_and_sync_navigation_data",
                "assemble_finish_temp",
                "run_noobscene_preprocessing",
                "run_initial_annotation_gui",
                "run_tracking",
                "prepare_gridmap_for_projection",
                "run_projection_and_trajectory",
                "validate_navigation_outputs",
            ],
        }

    def update(self, dataset_profile: str | None = None, profile: str | None = None) -> dict[str, Any]:
        self.validation_errors.clear()
        candidate_profile = dataset_profile or profile
        if candidate_profile is not None:
            try:
                get_profile(candidate_profile)
            except KeyError:
                self.validation_errors.append(
                    f"unsupported dataset_profile: {candidate_profile}; expected u_legacy_like or go2w_like"
                )
            else:
                self.dataset_profile = candidate_profile
        return self.status()

    def status(self) -> dict[str, Any]:
        return {
            "ok": not self.validation_errors,
            "draft": self.schema_snapshot(),
            "validation_errors": list(self.validation_errors),
        }


def build_plan_from_draft(state: WorkflowPlanDraftState) -> WorkflowPlan:
    from vla_data_juicer_agents.navigation.workflow import build_deterministic_plan_template

    if state.dataset_profile is None:
        raise ValueError("dataset_profile is required before finalizing WorkflowPlan")
    if state.scene_mode not in {"in", "out"}:
        raise ValueError("scene_mode is required before finalizing WorkflowPlan; expected 'in' or 'out'.")
    return build_deterministic_plan_template(state.date, state.dataset_profile, state.segments, scene_mode=state.scene_mode)


def build_plan_draft_tools(state: WorkflowPlanDraftState) -> list[FunctionTool]:
    def update_workflow_plan_draft_tool(
        dataset_profile: str | None = None,
        profile: str | None = None,
    ) -> dict[str, Any]:
        """Update the internal WorkflowPlan draft with newly inferred profile fields."""
        return state.update(dataset_profile=dataset_profile, profile=profile)

    def get_workflow_plan_draft_tool() -> dict[str, Any]:
        """Return the current WorkflowPlan draft schema, filled fields, missing fields, and validation errors."""
        return state.status()

    def finalize_workflow_plan_tool() -> dict[str, Any]:
        """Finalize and return strict WorkflowPlan JSON after the dataset profile has been validated."""
        plan = build_plan_from_draft(state)
        state.finalized_plan = plan
        return {
            "ok": True,
            "workflow_plan_json": json.loads(plan.model_dump_json()),
            "draft": state.schema_snapshot(),
        }

    return [
        FunctionTool(update_workflow_plan_draft_tool, name="update_workflow_plan_draft_tool", is_read_only=False),
        FunctionTool(get_workflow_plan_draft_tool, name="get_workflow_plan_draft_tool", is_read_only=True),
        FunctionTool(finalize_workflow_plan_tool, name="finalize_workflow_plan_tool", is_read_only=True),
    ]
